.gitignore and .gitattributes ... change bin/startSmalltalkServer to be gemstone3.x friendly with ideas from bin/startSmalltalkServer31

diff --git a/bin/startSmalltalkServer b/bin/startSmalltalkServer
--- a/bin/startSmalltalkServer
+++ b/bin/startSmalltalkServer
@@ -1,4 +1,12 @@
 #!/bin/bash
+#
+# ./startSmalltalkServer31 runs a server Gem
+#     - first argument is the name of the server class that will be looked up in Gemstone to startthe server
+#     - second argument is a port number
+#
+ServerClass=$1
+ServerPort=$2
+
 
 if [ -s $GEMSTONE/seaside/etc/gemstone.secret ]; then
     . $GEMSTONE/seaside/etc/gemstone.secret
@@ -13,7 +21,13 @@ if [ "a$1" = "a" ]; then
         exit 1
 fi
 
-cat << EOF | nohup $GEMSTONE/bin/topaz -l -T50000 2>&1 >> $GEMSTONE_LOGDIR/${1}_server-${2}.log &
+# Requires a port number as a parameter
+if [ "a$2" = "a" ]; then
+        echo 'Missing argument <server port number>'
+        exit 1
+fi
+
+cat << EOF | nohup $GEMSTONE/bin/topaz -l -e $GEMSTONE/seaside/etc/seaside30.conf 2>&1 >> $GEMSTONE_LOGDIR/${1}_server-${2}.log &
 
 set user DataCurator pass $GEMSTONE_CURATOR_PASS gems $GEMSTONE_NAME
 
@@ -40,21 +54,24 @@ System commitTransaction
 %
 
 run
-| count |
-true "enable for remote breakpoints and profiling"
+| x |
+"set _cacheName: for Gem to get unique id in statmon output. see http://code.google.com/p/glassdb/issues/detail?id=132"
+System _cacheName: ((x := '$1-' , (GsSession serialOfSession: System session) printString , '-' , System myUserProfile userId) copyFrom: 1 to: (x size min: 31)).
+%
+
+run
+
+GsProcess usingNativeCode not
   ifTrue: [
+    "Enable remote Breakpoing handling"
+    Breakpoint trappable: true.
     GemToGemAnnouncement installStaticHandler.
-    Exception
-      installStaticException:
-        [:ex :cat :num :args |
-          BreakpointNotification signal.
-          "needed to avoid infinite loop when resuming from a breakpoint"
-          ex _incrementBreakpointsToIgnore. ]
-      category: GemStoneError
-      number: 6005 "#rtErrCodeBreakpoint"
-      subtype: nil.
-   System commitTransaction ifFalse: [ nil error: 'Could not commit for GemToGemSignaling' ]].
-"System transactionMode: #manualBegin."
+    System commitTransaction 
+      ifFalse: [ nil error: 'Could not commit for GemToGemSignaling' ]. 
+  ].
+
+System transactionMode: #manualBegin.
+
 Exception
   installStaticException:
     [:ex :cat :num :args |
@@ -78,11 +95,15 @@ System enableSignaledAbortError.
   [ true ] whileTrue: [ (Delay forSeconds: 30) wait ].
 ] forkAt: Processor lowestPriority.
 
+GsFile gciLogServer: '$1 Server started on port ', $2 printString.
+
 WAGemStoneRunSmalltalkServer startGemServer: '$1' On: $2.
+"does not return"
 %
 run
 GemToGemAnnouncement uninstallStaticHandler.
-System beginTransaction.
+System inTransaction
+  ifFalse: [ System beginTransaction ].
 (ObjectLogEntry
   fatal: '${1}_server_${2}: topaz exit'
   object:
